[package]
name = "svg"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "svg_lib"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "=0.2.61"
tera = "1.2.0"
serde_json = "=1.0.44"
