[package]
name = "anagram_solver"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "anagram_solver_lib"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.61"
