[package]
name = "rkm"
version = "0.8.1"
authors = ["Nick Sarten <gen.battle@gmail.com>"]
description = "A generic k-means implementation"
repository = "https://github.com/genbattle/rkm"
readme = "README.md"
license = "MIT"
keywords = ["kmeans", "k-means", "means", "cluster", "clustering"]
categories = ["algorithms", "science"]
exclude = ["data/*"]
workspace = ".."
edition = "2018"

[features]
parallel = ["rayon", "ndarray/rayon"]

[dependencies]
rand = {version = "0.7.3", features = ["small_rng"]}
num = "0.2.1"
ndarray = "0.13.0"
cfg-if = "0.1.10"
rayon = {version = "1.3.0", optional = true}

[dev-dependencies]
csv = "1.1.3"
bencher = "0.1.5"
assert_approx_eq = "1.1.0"
plotters = "0.2.12"

[lib]
name = "rkm"
path = "src/lib.rs"

[[bench]]
name = "bench"
harness = false

# Use for debugging to work around https://github.com/rust-lang/cargo/issues/6301
# [profile.bench]
# opt-level = 0
# debug = 2
# debug-assertions = true
# overflow-checks = true