org: secondstate
app: poster-template
stage: prod

component: website
name: tf-website

inputs:
  src:
    src: ./content
    index: index.html
  region: ${env:region}
  protocol: https
  env:
      API_URL: https://${output:${stage}:${app}:tf-scf.triggers.0.subDomain}/${output:${stage}:${app}:tf-scf.triggers.0.environment}/
